import assert from 'node:assert/strict';
import { readdir, readFile } from 'node:fs/promises';
import test from 'node:test';

import matter from 'gray-matter';

const docs = new URL('../src/content/docs/', import.meta.url);

const expectedSidebar = [
	{ label: 'Understand', items: [{ autogenerate: { directory: 'understand' } }] },
	{
		label: 'Threat Model',
		items: [
			{ slug: 'threat-model', label: 'Overview' },
			'threat-model/introduction',
			'threat-model/threat-landscape',
			'threat-model/trust-boundaries',
			'threat-model/review-problem',
			{
				label: 'STRIDE',
				items: [
					{ slug: 'threat-model/stride', label: 'Overview' },
					'threat-model/stride/spoofing',
					'threat-model/stride/tampering',
					'threat-model/stride/repudiation',
					'threat-model/stride/information-disclosure',
					'threat-model/stride/denial-of-service',
					'threat-model/stride/elevation-of-privilege',
				],
			},
			'threat-model/guidance-gap',
			'threat-model/response-landscape',
			'threat-model/open-questions',
		],
	},
	{ label: 'ACF Taxonomy', items: [{ autogenerate: { directory: 'acf' } }] },
	{
		label: 'Wardline',
		items: [
			{ slug: 'wardline', label: 'Overview' },
			'wardline/what-a-wardline-is',
			'wardline/problem-and-non-goals',
			'wardline/trust-lattice',
			'wardline/declarations-and-trust-grants',
			{
				label: 'Rules',
				items: [
					{ slug: 'wardline/rules', label: 'Overview' },
					'wardline/rules/boundary-rules',
					'wardline/rules/sink-rules',
					'wardline/rules/rust-rules',
					'wardline/rules/engine-findings',
				],
			},
			'wardline/gates-suppression-and-judge',
			'wardline/verification',
			'wardline/residual-risks',
			'wardline/roadmap-the-unbuilt',
			'wardline/language-frontends',
			'wardline/python-reference',
		],
	},
	{ label: 'Assess', items: [{ autogenerate: { directory: 'assess' } }] },
	{ label: 'Respond', items: [{ autogenerate: { directory: 'respond' } }] },
	{ label: 'Appendices', items: [{ autogenerate: { directory: 'appendices' } }] },
	{ label: 'Reference', items: [{ autogenerate: { directory: 'reference' } }] },
];

test('sidebar encodes the complete intended reading order and nested group labels', async () => {
	const module = await import('../src/data/sidebar.mjs').catch(() => null);
	assert.ok(module, 'src/data/sidebar.mjs must define the intentional sidebar hierarchy');
	assert.deepEqual(module.sidebar, expectedSidebar);
});

test('Astro uses the reviewed sidebar hierarchy rather than inline autogeneration', async () => {
	const config = await readFile(new URL('../astro.config.mjs', import.meta.url), 'utf8');
	assert.match(config, /^import \{ sidebar \} from '\.\/src\/data\/sidebar\.mjs';$/m);
	assert.match(config, /^\s*sidebar,$/m);
});

async function contentDirectories(directory = docs) {
	const entries = await readdir(directory, { withFileTypes: true });
	const pages = entries.filter((entry) => entry.isFile() && /\.mdx?$/.test(entry.name));
	const nested = await Promise.all(
		entries
			.filter((entry) => entry.isDirectory())
			.map((entry) => contentDirectories(new URL(`${entry.name}/`, directory))),
	);
	return [{ directory, pages }, ...nested.flat()];
}

test('sibling pages have unique orders and every section overview comes first', async () => {
	for (const { directory, pages } of await contentDirectories()) {
		if (pages.length === 0 || directory.href === docs.href) continue;
		const metadata = await Promise.all(
			pages.map(async ({ name }) => ({ name, data: matter(await readFile(new URL(name, directory), 'utf8')).data })),
		);
		const ordered = metadata.filter(({ data }) => Number.isInteger(data.sidebar?.order));
		assert.equal(ordered.length, metadata.length, `${directory.pathname}: every page needs a sidebar order`);

		const orders = ordered.map(({ data }) => data.sidebar.order);
		assert.equal(new Set(orders).size, orders.length, `${directory.pathname}: sidebar orders must be unique`);

		const overview = ordered.find(({ name }) => /^index\.mdx?$/.test(name));
		if (overview) assert.equal(overview.data.sidebar.order, 0, `${directory.pathname}: overview must be first`);
	}
});

test('ACF sidebar labels use the canonical identifier and punctuation', async () => {
	const entries = await readdir(new URL('acf/', docs), { withFileTypes: true });
	for (const { name } of entries.filter((entry) => entry.isFile() && /\.mdx?$/.test(entry.name))) {
		const { data } = matter(await readFile(new URL(`acf/${name}`, docs), 'utf8'));
		if (!data.acf) continue;
		assert.equal(data.sidebar.label, `${data.acf.id}: ${data.acf.name}`, name);
	}
});

test('autogenerated section overview links use one concise label', async () => {
	for (const section of ['understand', 'assess', 'respond', 'appendices']) {
		const { data } = matter(await readFile(new URL(`${section}/index.md`, docs), 'utf8'));
		assert.equal(data.sidebar.label, 'Overview', section);
	}
});
